version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST=vpn.${WG_SERVER_HOST}
      - PASSWORD
      - WG_PORT
      # Optional:
      # - WG_DEFAULT_ADDRESS
      # - WG_DEFAULT_DNS
      # - WG_MTU
      # - WG_ALLOWED_IPS
      # - WG_PRE_UP
      # - WG_POST_UP
      # - WG_PRE_DOWN
      # - WG_POST_DOWN
      
    image: weejewel/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - ./wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
      # - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    labels:
      - sh.acme.autoload.domain=${WG_SERVER_HOST}
    volumes:
      - ./nginx:/etc/nginx
      - ./log/nginx:/var/log/nginx
    environment:
      - WG_SERVER_HOST

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    restart: unless-stopped


  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh    
    command: daemon
    volumes:
      - ./acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - DuckDNS_Token
    restart: unless-stopped
